dist: xenial
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"
install: pip install tox-travis coveralls
script:
    - tox
after_success:
    - coveralls
matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"
